package php.ast

sealed class ExprBinaryOp(open val left: Expr, open val right: Expr): Expr
data class ExprBinaryOpBitwiseAnd(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpBitwiseOr(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpBitwiseXor(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpBooleanAnd(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpBooleanOr(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpCoalesce(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpConcat(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpDiv(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpEqual(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpGreater(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpGreaterOrEqual(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpIdentical(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpLogicalAnd(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpLogicalOr(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpLogicalXor(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpMinus(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpMod(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpMul(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpNotEqual(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpNotIdentical(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpPlus(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpPow(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpShiftLeft(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpShiftRight(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpSmaller(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpSmallerOrEqual(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)
data class ExprBinaryOpSpaceship(override val left: Expr, override val right: Expr): ExprBinaryOp(left, right)