package kt.test

fun getConfig() = mapOf(
    "ExprArray" to listOf("items" to "List<ExprArrayItem?>"),
    "ExprArrayItem" to listOf("key" to "Expr?", "value" to "Expr", "byRef" to "Boolean", "unpack" to "Boolean"),
    "ExprExit" to listOf("expr" to "Expr?"),
    "ExprList" to listOf("items" to "List<ExprArrayItem?>"),
    "ExprTernary" to listOf("cond" to "Expr", "`if`" to "Expr?", "`else`" to "Expr"),
    "ExprThrow" to listOf("expr" to "Expr"),
    "ExprYield" to listOf("key" to "Expr?", "value" to "Expr?"),
    "ExprYieldFrom" to listOf("expr" to "Expr"),
    "ExprVariable.ExprVariableSimple" to listOf("name" to "String"),
    "ExprVariable.ExprVariableDynamic" to listOf("name" to "Expr"),
    "ExprInstanceof.ExprInstanceofName" to listOf("expr" to "Expr", "`class`" to "Name"),
    "ExprInstanceof.ExprInstanceofVariable" to listOf("expr" to "Expr", "`class`" to "ExprVariable"),
    "ExprAssign" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignRef" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpBitwiseAnd" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpBitwiseOr" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpBitwiseXor" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpConcat" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpDiv" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpMinus" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpMod" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpMul" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpPlus" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpPow" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpShiftLeft" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprAssignOpShiftRight" to listOf("`var`" to "Expr", "expr" to "Expr"),
    "ExprBinaryOpBitwiseAnd" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpBitwiseOr" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpBitwiseXor" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpBooleanAnd" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpBooleanOr" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpCoalesce" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpConcat" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpDiv" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpEqual" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpGreater" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpGreaterOrEqual" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpIdentical" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpLogicalAnd" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpLogicalOr" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpLogicalXor" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpMinus" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpMod" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpMul" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpNotEqual" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpNotIdentical" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpPlus" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpPow" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpShiftLeft" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpShiftRight" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpSmaller" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpSmallerOrEqual" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprBinaryOpSpaceship" to listOf("left" to "Expr", "right" to "Expr"),
    "ExprCastArray" to listOf("expr" to "Expr"),
    "ExprCastBool" to listOf("expr" to "Expr"),
    "ExprCastDouble" to listOf("expr" to "Expr"),
    "ExprCastInt" to listOf("expr" to "Expr"),
    "ExprCastObject" to listOf("expr" to "Expr"),
    "ExprCastString" to listOf("expr" to "Expr"),
    "ExprClosure" to listOf("static" to "Boolean", "byRef" to "Boolean", "params" to "List<Param>", "uses" to "List<ExprClosureUse>", "returnType" to "TypeHint?", "stmts" to "List<Stmt>"),
    "ExprClosureUse" to listOf("`var`" to "ExprVariable", "byRef" to "Boolean"),
    "FuncRef.FuncRefStatic" to listOf("`class`" to "Name"),
    "FuncRef.FuncRefDynamic" to listOf("`class`" to "Expr"),
    "ClassRef.ClassRefStatic" to listOf("name" to "Name"),
    "ClassRef.ClassRefDynamic" to listOf("name" to "Expr"),
    "PropertyRef.PropertyRefStatic" to listOf("name" to "Identifier"),
    "PropertyRef.PropertyRefDynamic" to listOf("name" to "Expr"),
    "MethodRef.MethodRefStatic" to listOf("name" to "Identifier"),
    "MethodRef.MethodRefDynamic" to listOf("name" to "Expr"),
    "ExprArrayDimFetch" to listOf("`var`" to "Expr", "dim" to "Expr?"),
    "ExprClassConstFetch" to listOf("`class`" to "ClassRef", "name" to "Identifier"),
    "ExprConstFetch" to listOf("name" to "Name"),
    "ExprPropertyFetch" to listOf("`var`" to "Expr", "name" to "PropertyRef"),
    "ExprStaticPropertyFetch" to listOf("`class`" to "ClassRef", "name" to "PropertyRef"),
    "ExprFuncCall" to listOf("name" to "FuncRef", "args" to "List<Arg>"),
    "ExprMethodCall" to listOf("`var`" to "Expr", "name" to "MethodRef", "args" to "List<Arg>"),
    "ExprStaticCall" to listOf("`class`" to "ClassRef", "name" to "MethodRef", "args" to "List<Arg>"),
    "ExprNew.ExprNewStatic" to listOf("`class`" to "Name", "args" to "List<Arg>"),
    "ExprNew.ExprNewDynamic" to listOf("`class`" to "Expr", "args" to "List<Arg>"),
    "ExprNew.ExprNewAnonymous" to listOf("`class`" to "StmtClass", "args" to "List<Arg>"),
    "ExprEmpty" to listOf("expr" to "Expr"),
    "ExprInclude" to listOf("expr" to "Expr", "type" to "Int"),
    "ExprIsset" to listOf("vars" to "List<Expr>"),
    "ExprClone" to listOf("expr" to "Expr"),
    "ExprBitwiseNot" to listOf("expr" to "Expr"),
    "ExprBooleanNot" to listOf("expr" to "Expr"),
    "ExprErrorSuppress" to listOf("expr" to "Expr"),
    "ExprPostDec" to listOf("`var`" to "Expr"),
    "ExprPostInc" to listOf("`var`" to "Expr"),
    "ExprPreDec" to listOf("`var`" to "Expr"),
    "ExprPreInc" to listOf("`var`" to "Expr"),
    "ExprPrint" to listOf("expr" to "Expr"),
    "ExprUnaryMinus" to listOf("expr" to "Expr"),
    "ExprUnaryPlus" to listOf("expr" to "Expr"),
    "Arg" to listOf("value" to "Expr", "byRef" to "Boolean", "unpack" to "Boolean"),
    "Param" to listOf("type" to "TypeHint?", "byRef" to "Boolean", "variadic" to "Boolean", "`var`" to "ExprVariable", "default" to "Expr?"),
    "TypeHint" to listOf("name" to "String", "nullable" to "Boolean", "isBuiltin" to "Boolean"),
    "Identifier" to listOf("name" to "String", "varLike" to "Boolean"),
    "Name" to listOf("parts" to "List<String>", "fullyQualified" to "Boolean"),
    "ScalarDNumber" to listOf("value" to "Double"),
    "ScalarEncapsed" to listOf("parts" to "List<Expr>"),
    "ScalarEncapsedStringPart" to listOf("value" to "String"),
    "ScalarLNumber" to listOf("value" to "Int"),
    "ScalarString" to listOf("value" to "String"),
    "ScalarMagicConstClass" to listOf(),
    "ScalarMagicConstDir" to listOf(),
    "ScalarMagicConstFile" to listOf(),
    "ScalarMagicConstFunction" to listOf(),
    "ScalarMagicConstLine" to listOf(),
    "ScalarMagicConstMethod" to listOf(),
    "ScalarMagicConstNamespace" to listOf(),
    "ScalarMagicConstTrait" to listOf(),
    "StmtConst" to listOf("name" to "Name", "value" to "Expr"),
    "StmtDeclare" to listOf("declares" to "List<Pair<Identifier, Expr>>", "stmts" to "List<Stmt>?"),
    "StmtNamespace" to listOf("name" to "Name?", "stmts" to "List<Stmt>"),
    "StmtEcho" to listOf("exprs" to "List<Expr>"),
    "StmtExpression" to listOf("expr" to "Expr"),
    "StmtFunction" to listOf("byRef" to "Boolean", "name" to "Identifier", "params" to "List<Param>", "returnType" to "TypeHint?", "stmts" to "List<Stmt>", "namespacedName" to "Name"),
    "StmtGlobal" to listOf("vars" to "List<Expr>"),
    "StmtInlineHTML" to listOf("value" to "String"),
    "StmtNop" to listOf(),
    "StmtStatic" to listOf("vars" to "List<StmtStaticVar>"),
    "StmtStaticVar" to listOf("`var`" to "ExprVariable", "default" to "Expr?"),
    "StmtUnset" to listOf("vars" to "List<Expr>"),
    "StmtClassConst" to listOf("flags" to "Int", "name" to "Identifier", "value" to "Expr"),
    "StmtProperty" to listOf("flags" to "Int", "name" to "Identifier", "default" to "Expr?"),
    "StmtClassMethod" to listOf("flags" to "Int", "byRef" to "Boolean", "name" to "Identifier", "params" to "List<Param>", "returnType" to "TypeHint?", "stmts" to "List<Stmt>?"),
    "StmtClass" to listOf("flags" to "Int", "extends" to "Name?", "implements" to "List<Name>", "name" to "Identifier?", "stmts" to "List<Stmt>", "namespacedName" to "Name"),
    "StmtInterface" to listOf("extends" to "List<Name>", "name" to "Identifier", "stmts" to "List<Stmt>", "namespacedName" to "Name"),
    "StmtTrait" to listOf("name" to "Identifier", "stmts" to "List<Stmt>", "namespacedName" to "Name"),
    "StmtBreak" to listOf("num" to "Expr?"),
    "StmtContinue" to listOf("num" to "Expr?"),
    "StmtReturn" to listOf("expr" to "Expr?"),
    "StmtThrow" to listOf("expr" to "Expr"),
    "StmtLabel" to listOf("name" to "Identifier"),
    "StmtGoto" to listOf("name" to "Identifier"),
    "StmtIf" to listOf("branches" to "List<Pair<Expr, List<Stmt>>>", "defaultBranch" to "List<Stmt>?"),
    "StmtSwitch" to listOf("cond" to "Expr", "cases" to "List<Pair<Expr?, List<Stmt>>>"),
    "StmtTryCatch" to listOf("stmts" to "List<Stmt>", "catches" to "List<CatchBranch>", "finally" to "List<Stmt>?"),
    "StmtFor" to listOf("init" to "List<Expr>", "cond" to "List<Expr>", "loop" to "List<Expr>", "stmts" to "List<Stmt>"),
    "StmtForeach" to listOf("expr" to "Expr", "keyVar" to "Expr?", "byRef" to "Boolean", "valueVar" to "Expr", "stmts" to "List<Stmt>"),
    "StmtWhile" to listOf("cond" to "Expr", "stmts" to "List<Stmt>"),
    "StmtDo" to listOf("stmts" to "List<Stmt>", "cond" to "Expr"),
    "StmtTraitUse" to listOf("traits" to "List<Name>", "adaptations" to "List<StmtTraitUseAdaptation>"),
    "StmtTraitUseAdaptationAlias" to listOf("newModifier" to "Int?", "newName" to "Identifier?", "trait" to "Name?", "method" to "Identifier"),
    "StmtTraitUseAdaptationPrecedence" to listOf("insteadof" to "List<Name>", "trait" to "Name?", "method" to "Identifier"),
)